Dimensions picker preparations
apepper/scrivito-portal-app pull request #2
Opened 2024-12-04 13:15 UTC by agessler

See video for details. In chrome not tested yet.

2024-12-13 11:05 UTC, apepper reviewed
FEEDBACK ([30d93ce](https://github.com/apepper/scrivito-portal-app/pull/2/commits/30d93ce614c58a03559edb473ec90865b9822cbb))

Very nice start 🚀!

Please see my comments on how this can be improved even further.

2024-12-13 11:05 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +              <input type="text" placeholder="100" />
Please make this `type="number"`. Also please hide the "up/down" arrows that the browser will then render (at least Chrome). (for both inputs)

2024-12-13 11:05 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +              <input type="text" placeholder="100" />
Please add `min="0"`.

2024-12-13 11:05 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +              <input type="text" placeholder="100" />
For me to later on add: `max="100"` for `%` and `max="33000000"` for `px`(see https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties)

2024-12-13 11:05 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +            <div class="attribute-preview contain"></div>
There is no `class` in `react`, only `className`. Please adjust (three times).

2024-12-13 11:05 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +            <div className="input_group">
Could you add the nice "full box" highlight style as dartagnan is using?

![Screenshot 2024-12-13 at 11 58 15](https://github.com/user-attachments/assets/2666293d-6f67-4dcb-9334-474c44decbe2)

Currently only the input field itself is highlighted, not the select box as well:
![Screenshot 2024-12-13 at 12 01 09](https://github.com/user-attachments/assets/03e7e0f4-3bd9-40fc-b9ed-5d82b1602a1b)

Two more observations:
* The inner spacing could be improved.
* Dartagnan limits the width of the element to 100px, which looks quite nice.

2024-12-13 11:54 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +        </ul>
Sorry for the belated response - I just noticed this now.

Please also add `none` and `scale-down` to support all currently know values of "object-fit" - see https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#try_it

2025-01-17 09:19 UTC, agessler commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +        </ul>
@apepper  Possible to add but the question who uses these features? I only want to offer settings that are really in use. `none` would be initially right but seems that it will be always a kind of broken. `scale-down` seems to me a esoteric.

2025-01-17 09:23 UTC, agessler commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +            <div className="input_group">
Possible but I have to change a lot CSS for different highlighting.

2025-01-17 09:40 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +        </ul>
I would rather support all values, if they are not esoteric. `scale-down` reads useful:

> [scale-down](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#scale-down)
> The content is sized as if none or contain were specified, whichever would result in a smaller concrete object size.

2025-01-17 09:41 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +            <div className="input_group">
I would prefer more the look of Dartagnan.

2025-02-05 12:33 UTC, agessler commented
@apepper ![img-widget](https://github.com/user-attachments/assets/6304cb64-1230-473f-bd59-71b3472f5e3e)

2025-02-05 12:50 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +            <div className="input_group">
The two observations are still present:

> Two more observations:
>
> * The inner spacing could be improved.
> * Dartagnan limits the width of the element to 100px, which looks quite nice.

2025-02-05 12:53 UTC, apepper requested changes
FEEDBACK ([861b87e](https://github.com/apepper/scrivito-portal-app/pull/2/commits/861b87e64f4b969c33a94de203e9981817aa1446))

Nice 🚀 

There are still two open topics:

* [ ] https://github.com/apepper/scrivito-portal-app/pull/2#discussion_r1942886822
* [x] The comment from below (up/down buttons).

2025-02-05 12:53 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +              <input type="number" min="0" max="100" placeholder="100" />
At least brave is showing me "ugly" up/down buttons:
<img width="517" alt="Screenshot 2025-02-05 at 13 51 27" src="https://github.com/user-attachments/assets/4ee9fbba-005b-4bd2-9427-2c198552f80a" />

I suspect that Chrome does the same. Please remove them.

2025-02-05 12:55 UTC, agessler commented on src/Widgets/ImageWidget/DimensionsPicker.tsx
> +              <input type="number" min="0" max="100" placeholder="100" />
I thought my CSS took both.. 😞
`appearance: textfield;
    -webkit-appearance: textfield;`

2025-02-06 09:24 UTC, apepper requested changes
FEEDBACK ([6223ccf](https://github.com/apepper/scrivito-portal-app/pull/2/commits/6223ccf8444590d7ee361d63cb8046a08511f45f))

Almost there. I found one more 1px issue (see comments below).

2025-02-06 09:24 UTC, apepper commented on src/Widgets/ImageWidget/DimensionsPicker.scss
> +    border-radius: 2px;
I think this should be `3px`. At least there is a small inner gab at the round boarder:

![Screenshot 2025-02-06 at 10 14 57](https://github.com/user-attachments/assets/39d9d1ba-2482-46db-82cf-9b3959e61a78)

2025-02-06 11:05 UTC, apepper approved these changes
LGTM ([3278dc8](https://github.com/apepper/scrivito-portal-app/pull/2/commits/3278dc8a7a14ec789c79bc5c06767343e0aedd68))

Nice 🚀!

2025-02-06 11:05 UTC, merged